version: "3.3"

services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    stdin_open: true
    restart: always
    environment:
      POSTGRES_PASSWORD: 2828
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ../data:/data

