CREATE SCHEMA FITNESS;
CREATE TABLE FITNESS.PROGRAM(
    ID           SERIAL,
    PROGRAM_NM   VARCHAR(100)    NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE FITNESS.EXERCISE(
    ID      SERIAL,
    EXERCISE_NM    VARCHAR(100)    NOT NULL,
    MUSCLES_NM VARCHAR(200)    NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE FITNESS.ITEM(
    ID      SERIAL,
    ITEM_TITLE    VARCHAR(100)    NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE FITNESS.GYM(
    ID      SERIAL,
    GYM_TITLE    VARCHAR(200)    NOT NULL,
    CLUB_NM    VARCHAR(200)    NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE FITNESS.TRAINER(
    ID      SERIAL,
    TRAINER_NM    VARCHAR(100)    NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE FITNESS.ATHLETE(
    ID      SERIAL,
    ATHLETE_NM    VARCHAR(100)    NOT NULL,
    TRAINER_ID INT,
    PROGRAM_ID INT          NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (TRAINER_ID) REFERENCES FITNESS.TRAINER(ID),
    FOREIGN KEY (PROGRAM_ID) REFERENCES FITNESS.PROGRAM(ID)
);

CREATE TABLE FITNESS.PROGRAM_X_EXERCISE(
    EXERCISE_ID INT,
    PROGRAM_ID INT,
    PRIMARY KEY (EXERCISE_ID, PROGRAM_ID),
    FOREIGN KEY (EXERCISE_ID) REFERENCES FITNESS.EXERCISE(ID),
    FOREIGN KEY (PROGRAM_ID) REFERENCES FITNESS.PROGRAM(ID)
);

CREATE TABLE FITNESS.EXERCISE_X_ITEM(
    EXERCISE_ID INT,
    ITEM_ID INT,
    PRIMARY KEY (EXERCISE_ID, ITEM_ID),
    FOREIGN KEY (EXERCISE_ID) REFERENCES FITNESS.EXERCISE(ID),
    FOREIGN KEY (ITEM_ID) REFERENCES FITNESS.ITEM(ID)
);

CREATE TABLE FITNESS.ATHLETE_X_GYM(
    ATHLETE_ID INT,
    GYM_ID INT,
    PRIMARY KEY (ATHLETE_ID, GYM_ID),
    FOREIGN KEY (ATHLETE_ID) REFERENCES FITNESS.ATHLETE(ID),
    FOREIGN KEY (GYM_ID) REFERENCES FITNESS.GYM(ID)
);

CREATE TABLE FITNESS.TRAINER_X_GYM(
    TRAINER_ID INT,
    GYM_ID INT,
    PRIMARY KEY (TRAINER_ID, GYM_ID),
    FOREIGN KEY (TRAINER_ID) REFERENCES FITNESS.TRAINER(ID),
    FOREIGN KEY (GYM_ID) REFERENCES FITNESS.GYM(ID)
);

CREATE TABLE FITNESS.GYM_X_ITEM(
    ITEM_ID INT,
    GYM_ID INT,
    VALID_FROM_DTTM   TIMESTAMP DEFAULT now() NOT NULL,
    VALID_TO_DTTM     TIMESTAMP DEFAULT TO_TIMESTAMP('5999-01-01', 'YYYY-MM-DD') NOT NULL,
    PRIMARY KEY (ITEM_ID, GYM_ID, VALID_FROM_DTTM),
    FOREIGN KEY (ITEM_ID) REFERENCES FITNESS.ITEM(ID),
    FOREIGN KEY (GYM_ID) REFERENCES FITNESS.GYM(ID)
);